//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListMotor()
        {
            this.Measreds = new HashSet<Measred>();
        }
    
        public int Id { get; set; }
        public string Motor_Name { get; set; }
        public string Type { get; set; }
        public int Max_power__kW_ { get; set; }
        public Nullable<int> Voltage__V_ { get; set; }
        public Nullable<decimal> Current__A_ { get; set; }
        public Nullable<int> Fuel_consumtion_per_hour_l_h_ { get; set; }
        public Nullable<int> Max_torque_at__rpm_ { get; set; }
        public Nullable<int> Max_presure__bar_ { get; set; }
        public Nullable<int> Displacement__cm3_rev_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measred> Measreds { get; set; }
    }
}
