//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measred
    {
        public int Id { get; set; }
        public System.TimeSpan Time_of_measurement { get; set; }
        public Nullable<decimal> Actual_current__A_ { get; set; }
        public Nullable<int> Actual_revs___rpm_ { get; set; }
        public Nullable<int> Actual_pressure__bar_ { get; set; }
        public Nullable<int> MotorsId { get; set; }
    
        public virtual ListMotor ListMotor { get; set; }
    }
}
